# Generated by Django 4.2.25 on 2025-10-05 19:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("dataset_file", models.CharField(max_length=255)),
                ("n_samples", models.IntegerField()),
                ("n_features", models.IntegerField()),
                ("rf_n_estimators", models.IntegerField(default=200)),
                ("gb_n_estimators", models.IntegerField(default=200)),
                ("gb_learning_rate", models.FloatField(default=0.1)),
                ("test_size", models.FloatField(default=0.3)),
                ("accuracy", models.FloatField(null=True)),
                ("f1_score", models.FloatField(null=True)),
                ("roc_auc", models.FloatField(null=True)),
                ("balanced_accuracy", models.FloatField(null=True)),
                ("training_time", models.FloatField(null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("koi_id", models.CharField(max_length=100)),
                ("predicted_class", models.CharField(max_length=20)),
                ("confidence", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "model_training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="classifier.modeltraining",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence"],
            },
        ),
    ]
